version: "3.7"
services:
  maternity-proxy:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: maternity-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt

  maternity-redis:
    image: redis:7.2-alpine
    container_name: maternity-redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - maternity_care_system_g44

  maternity-mariadb:
    image: mariadb:10.11   # LTS stable, matches current running container
    container_name: maternity-mariadb
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - maternity_care_system_g44
  maternity-mysql-backup:
    image: fradelg/mysql-cron-backup
    container_name: maternity-mysql-backup
    restart: unless-stopped
    environment:
      - MYSQL_HOST=maternity-mariadb
      - MYSQL_PORT=3306
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_DUMP_FREQ=30
      - MYSQL_DUMP_DATABASE=${MARIADB_DATABASE}
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./mariadb/backups:/backup
    depends_on:
      - maternity-mariadb
    networks:
      - maternity_care_system_g44

networks:
  maternity_care_system_g44:
    name: maternity_care_system_g44
    driver: bridge
